server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:file:./data/authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.security: DEBUG
